### ISSUE TITLE
Problem building environment

### ISSUE THREAD

**Issue by dhvalden** [firojalam/COVID-19-disinformation#1]
I have found a problems building the environment to reproduce the experiments

Steps to reproduce:
Run: 
``cd /your_path/exp_covid19_disinfo/
conda env create -f bin/covid_exp_env.yml
source activate $path_to_your_env/transformers``

```
Error message:
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/apps/developers/compilers/anaconda/2019.10/1/default/lib/python3.7/site-packages/conda/exceptions.py", line 1074, in __call__
        return func(*args, **kwargs)
      File "/apps/developers/compilers/anaconda/2019.10/1/default/lib/python3.7/site-packages/conda_env/cli/main.py", line 78, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/apps/developers/compilers/anaconda/2019.10/1/default/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 102, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/apps/developers/compilers/anaconda/2019.10/1/default/lib/python3.7/site-packages/conda_env/installers/conda.py", line 26, in install
        solver = Solver(prefix, channels, subdirs, specs_to_add=specs)
      File "/apps/developers/compilers/anaconda/2019.10/1/default/lib/python3.7/site-packages/conda/core/solve.py", line 71, in __init__
        self.specs_to_add = frozenset(MatchSpec.merge(s for s in specs_to_add))
      File "/apps/developers/compilers/anaconda/2019.10/1/default/lib/python3.7/site-packages/conda/models/match_spec.py", line 467, in merge
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/apps/developers/compilers/anaconda/2019.10/1/default/lib/python3.7/site-packages/conda/models/match_spec.py", line 467, in <lambda>
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/apps/developers/compilers/anaconda/2019.10/1/default/lib/python3.7/site-packages/conda/models/match_spec.py", line 498, in _merge
        final = this_component.merge(that_component)
      File "/apps/developers/compilers/anaconda/2019.10/1/default/lib/python3.7/site-packages/conda/models/match_spec.py", line 751, in merge
        % (self.raw_value, other.raw_value))
    ValueError: Incompatible component merge:
      - 'py36_0'
      - 'py37_0'

`$ /apps/developers/compilers/anaconda/2019.10/1/default/bin/conda-env create -f ../bin/covid_exp_env.yml`

  environment variables:
                 CIO_TEST=<not set>
                CLASSPATH=/apps/developers/compilers/intel/19.0.4/1/default/compilers_and_librar
                          ies_2019.4.243/linux/daal/lib/daal.jar
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/apps/developers/compilers/anaconda/2019.10/1/default/bin/conda
             CONDA_PREFIX=/apps/developers/compilers/anaconda/2019.10/1/default
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/apps/developers/compilers/anaconda/2019.10/1/default/bin/python
               CONDA_ROOT=/apps/developers/compilers/anaconda/2019.10/1/default
              CONDA_SHLVL=1
                    CPATH=/apps/developers/libraries/openmpi/3.1.4/1/intel-19.0.4/include:/apps/
                          developers/compilers/intel/19.0.4/1/default/compilers_and_libraries_20
                          19.4.243/linux/ipp/include:/apps/developers/compilers/intel/19.0.4/1/d
                          efault/compilers_and_libraries_2019.4.243/linux/pstl/include:/apps/dev
                          elopers/compilers/intel/19.0.4/1/default/compilers_and_libraries_2019.
                          4.243/linux/tbb/include:/apps/developers/compilers/intel/19.0.4/1/defa
                          ult/compilers_and_libraries_2019.4.243/linux/daal/include
                 INFOPATH=/apps/developers/compilers/intel/19.0.4/1/default/documentation_2019/e
                          n/debugger/gdb-ia/info/
          LD_LIBRARY_PATH=/apps/developers/libraries/openmpi/3.1.4/1/intel-19.0.4/lib:/apps/deve
                          lopers/compilers/intel/19.0.4/1/default/compilers_and_libraries_2019.4
                          .243/linux/ipp/lib/intel64:/apps/developers/compilers/intel/19.0.4/1/d
                          efault/compilers_and_libraries_2019.4.243/linux/compiler/lib/intel64_l
                          in:/apps/developers/compilers/intel/19.0.4/1/default/compilers_and_lib
                          raries_2019.4.243/linux/tbb/lib/intel64/gcc4.7:/apps/developers/compil
                          ers/intel/19.0.4/1/default/debugger_2019/libipt/intel64/lib:/apps/deve
                          lopers/compilers/intel/19.0.4/1/default/compilers_and_libraries_2019.4
                          .243/linux/daal/lib/intel64_lin:/apps/developers/compilers/intel/19.0.
                          4/1/default/compilers_and_libraries_2019.4.243/linux/daal/../tbb/lib/i
                          ntel64_lin/gcc4.4:/services/sge_prod/lib/lx-amd64
             LIBRARY_PATH=/apps/developers/libraries/openmpi/3.1.4/1/intel-19.0.4/lib:/apps/deve
                          lopers/compilers/intel/19.0.4/1/default/compilers_and_libraries_2019.4
                          .243/linux/ipp/lib/intel64:/apps/developers/compilers/intel/19.0.4/1/d
                          efault/compilers_and_libraries_2019.4.243/linux/compiler/lib/intel64_l
                          in:/apps/developers/compilers/intel/19.0.4/1/default/compilers_and_lib
                          raries_2019.4.243/linux/tbb/lib/intel64/gcc4.7:/apps/developers/compil
                          ers/intel/19.0.4/1/default/compilers_and_libraries_2019.4.243/linux/da
                          al/lib/intel64_lin:/apps/developers/compilers/intel/19.0.4/1/default/c
                          ompilers_and_libraries_2019.4.243/linux/daal/../tbb/lib/intel64_lin/gc
                          c4.4
                  MANPATH=/apps/developers/libraries/openmpi/3.1.4/1/intel-19.0.4/share/man:/app
                          s/developers/compilers/intel/19.0.4/1/default/man/common:/apps/develop
                          ers/compilers/intel/19.0.4/1/default/documentation_2019/en/debugger/gd
                          b-ia/man/:/services/sge_prod/man:/usr/man::/usr/man:
               MODULEPATH=/apps/Modules/infrastructure:/apps/Modules/developers/architecture:/ap
                          ps/Modules/developers/compilers:/apps/Modules/developers/libraries:/ap
                          ps/Modules/applications
                  NLSPATH=/apps/developers/compilers/intel/19.0.4/1/default/compilers_and_librar
                          ies_2019.4.243/linux/compiler/lib/intel64/locale/%l_%t/%N:/apps/develo
                          pers/compilers/intel/19.0.4/1/default/debugger_2019/gdb/intel64/share/
                          locale/%l_%t/%N
                     PATH=/apps/developers/compilers/anaconda/2019.10/1/default/bin:/apps/develo
                          pers/compilers/anaconda/2019.10/1/default/bin:/apps/developers/compile
                          rs/anaconda/2019.10/1/default/bin:/apps/developers/compilers/anaconda/
                          2019.10/1/default/condabin:/apps/developers/compilers/anaconda/2019.10
                          /1/default/bin:/apps/mpi/bin:/apps/developers/libraries/openmpi/3.1.4/
                          1/intel-19.0.4/bin:/apps/developers/compilers/intel/19.0.4/1/default/c
                          ompilers_and_libraries_2019.4.243/linux/bin/intel64:/apps/developers/c
                          ompilers/intel/19.0.4/1/default/debugger_2019/gdb/intel64/bin:/service
                          s/sge_prod/bin/lx-amd64:/services/sge_prod/default/common/leeds/bin:/u
                          sr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:
                          /opt/puppetlabs/bin:/apps/bin:/home/home01/ptdhv/.local/bin:/home/home
                          01/ptdhv/bin:/apps/bin:/home/home01/ptdhv/.local/bin:/home/home01/ptdh
                          v/bin
          PKG_CONFIG_PATH=/apps/developers/libraries/openmpi/3.1.4/1/intel-19.0.4/lib/pkgconfig
           QT_PLUGIN_PATH=/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               TCLLIBPATH=/apps/Modules/common

     active environment : base
    active env location : /apps/developers/compilers/anaconda/2019.10/1/default
            shell level : 1
       user config file : /home/home01/ptdhv/.condarc
 populated config files : /home/home01/ptdhv/.condarc
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages : 
       base environment : /apps/developers/compilers/anaconda/2019.10/1/default  (read only)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /apps/developers/compilers/anaconda/2019.10/1/default/pkgs
                          /home/home01/ptdhv/.conda/pkgs
       envs directories : /home/home01/ptdhv/.conda/envs
                          /apps/developers/compilers/anaconda/2019.10/1/default/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Linux/3.10.0-1160.45.1.el7.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 471018:13255
             netrc file : None
           offline mode : False
```

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

The errors seems to related to two version of python under the same env.

**Comment by dhvalden** [comment]
Solved this particular issue by editing the yml file and removing all conflicting dependencies. However, fasttext failed to build via pip, and i installed via conda. Not ideal.

**Comment by firojalam** [comment]
> Solved this particular issue by editing the yml file and removing all conflicting dependencies. However, fasttext failed to build via pip, and i installed via conda. Not ideal.

Hi @dhvalden,
Thanks and I am glad that you fixed it. 
Can you please push the env file? Might be useful to others. 

Thanks again

Firoj

**Comment by dhvalden** [comment]
added a pull request!

Thanks a lot!
